language: node_js
node_js:
- '4.6.1'
before_script:
- npm install -g mocha
- echo '{"network":"testnet", "privateSeed":"'$PRIVATE_SEED'"}' >> test/settings.json
after_script:
- npm run coverage
- npm run coveralls
